version: "3.3"
services:
  streaming-platform-keycloak:
    image: jboss/keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command: ["-Djboss.socket.binding.port-offset=100 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"]
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin1
    restart: always
    ports:
      - "8180:8180"
    expose:
      - 8180

  streaming-platform-backend:
    image: streaming-platform-backend
    restart: always
    ports:
      - "8082:8082"
    expose:
      - 8082
    depends_on:
      - streaming-platform-keycloak


  streaming-platform-frontend:
    image: streaming-platform-frontend
    restart: always
    ports:
      - "4500:80"
    expose:
      - 4500
      - 80
    depends_on:
      - streaming-platform-backend
